export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCHED_ERROR: "PROFILE_DATA_FETCHED_ERROR",
    USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
    IMAGE_UPDATED: "IMAGE_UPDATED",
  },
  post: {
    DATA_FETCHING: "POST_DATA_FETCHING",
    DATA_FETCHED: "POST_DATA_FETCHED",
    DATA_FETCHED_ERROR: "POST_DATA_FETCHED_ERROR",
    DATA_CREATED: "POST_DATA_CREATED",
    DATA_EDITED: "POST_DATA_EDITED",
    DATA_DELETED: "POST_DATA_DELETED",
  },
};
